<?php

namespace Woody\System;

use \Utils\Geom\Dimension;

/**
 * Test class for WindowConstraints.
 * Generated by PHPUnit on 2012-05-03 at 18:00:04.
 */
class WindowConstraintsTest extends \PHPUnit_Framework_TestCase {
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {

  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * This method tests getting the instance from the singleton class.
   *
   * @covers \Woody\System\WindowConstraints::getInstance
   * @covers \Woody\System\WindowConstraints::__construct
   * @covers \Woody\System\WindowConstraints::determineMinima
   */
  public function testGetInstance() {
    $this->assertInstanceOf('Woody\System\WindowConstraints', WindowConstraints::getInstance());
  }

  /**
   * @covers \Woody\System\WindowConstraints::enforceConstraints
   */
  public function testEnsureMinimalDimension() {
    $windowConstraints  = WindowConstraints::getInstance();
    $dimension          = $windowConstraints->enforceConstraints($dimension = new Dimension(0, 0));

    $this->assertGreaterThan(0, $dimension->width);
    $this->assertGreaterThan(0, $dimension->height);
  }
}