<?php

namespace Woody;

use Utils\Geom\Dimension;
use Utils\Geom\Point;
use Woody\Components\Windows\MainWindow;

/**
 * Test class for WinBinderErrorException.
 * Generated by PHPUnit on 2012-07-05 at 22:15:52.
 */
class WinBinderErrorExceptionTest extends \PHPUnit_Framework_TestCase {
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests raising the exception.
   *
   * @covers \Woody\WinBinderErrorException::__construct
   */
  public function testConstruct() {
    $window = new MainWindow('TestApp', new Point(50, 50), new Dimension(300, 200));

    try {
      // refreshing the window before it was created will lead to a winbinder exception
      $window->refresh();
    } catch(WinBinderErrorException $exception) {
      $this->assertInstanceOf('\Woody\WinBinderErrorException', $exception);
      return;
    }

    $this->fail('The expected \Woody\WinBinderErrorException has not been raised.');
  }
}