<?php

namespace Woody\Dialog\FileSystem;

/**
 * Test class for FileFilters.
 * Generated by PHPUnit on 2012-07-02 at 21:42:17.
 */
class FileFiltersTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var FileFilters
   */
  protected $filters = null;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests creating the filter.
   *
   * @covers FileFilters::__construct
   */
  public function testConstruct() {
    $this->filters = new FileFilters();

    $this->assertInstanceOf('\Woody\Dialog\FileSystem\FileFilters', $this->filters);
  }

  /**
   * This method tests adding filters and getting them in array representation.
   *
   * @covers FileFilters::add
   * @covers FileFilters::toArray
   */
  public function testAdd() {
    $this->filters = new FileFilters();

    $this->filters->add('PHP files', '*.php');
    $this->filters->add('PHP includes', '*.inc');
    $this->filters->add('HTML files', '*.htm?');

    $expected = array(
      array('PHP files', '*.php'),
      array('PHP includes', '*.inc'),
      array('HTML files', '*.htm?')
    );

    $this->assertEquals($expected, $this->filters->toArray());
  }
}