<?php

namespace ws\loewe\Woody\Dialog\FileSystem;

/**
 * Test class for FileSaveDialog.
 * Generated by PHPUnit on 2012-07-02 at 21:42:18.
 */
class FileSaveDialogTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var FileSaveDialog
   */
  private $dialog = null;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests creating the dialog.
   *
   * @covers \ws\loewe\Woody\Dialog\FileSystem\FileSaveDialog::__construct
   * @covers \ws\loewe\Woody\Dialog\FileSystem\FileSystemDialog::__construct
   */
  public function testConstruct() {
    $this->dialog = new FileSaveDialog('testConstruct', null, '.', null);

    $this->assertInstanceOf('\ws\loewe\Woody\Dialog\FileSystem\FileSaveDialog', $this->dialog);
  }
}