<?php

namespace ws\loewe\Woody\Dialog\FileSystem;

/**
 * Test class for FolderSelectDialog.
 * Generated by PHPUnit on 2012-07-02 at 21:42:18.
 */
class FolderSelectDialogTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var FolderSelectDialog
   */
  private $dialog = null;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests creating the dialog.
   *
   * @covers \ws\loewe\Woody\Dialog\FileSystem\FolderSelectDialog::__construct
   * @covers \ws\loewe\Woody\Dialog\FileSystem\FileSystemDialog::__construct
   */
  public function testConstruct() {
    $this->dialog = new FolderSelectDialog('testConstruct', null, '.');

    $this->assertInstanceOf('\ws\loewe\Woody\Dialog\FileSystem\FolderSelectDialog', $this->dialog);
  }
}
