<?php

namespace ws\loewe\Woody\Dialog\Notification;

/**
 * Test class for OkCancelConfirmationDialog.
 * Generated by PHPUnit on 2012-07-02 at 23:35:13.
 */
class OkCancelConfirmationDialogTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var OkCancelConfirmationDialog
   */
  protected $dialog;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests creating the dialog.
   *
   * @covers \ws\loewe\Woody\Dialog\Notification\OkCancelConfirmationDialog::__construct
   * @covers \ws\loewe\Woody\Dialog\Notification\ConfirmationDialog::__construct
   * @covers \ws\loewe\Woody\Dialog\Notification\ModalSystemDialog::__construct
   */
  public function testConstruct() {
    $this->dialog = new OkCancelConfirmationDialog('testConstruct', 'testConstruct', null);

    $this->assertInstanceOf('\ws\loewe\Woody\Dialog\Notification\OkCancelConfirmationDialog', $this->dialog);
  }

  /**
   * This method tests getting the initial state of the dialog.
   *
   * @covers \ws\loewe\Woody\Dialog\Notification\OkCancelConfirmationDialog::ok
   * @covers \ws\loewe\Woody\Dialog\Notification\OkCancelConfirmationDialog::cancel
   */
  public function testOkCancel() {
    $this->dialog = new OkCancelConfirmationDialog('testConstruct', 'testConstruct', null);

    $this->assertFalse($this->dialog->ok());
    $this->assertFalse($this->dialog->cancel());
  }
}