<?php

namespace Woody\Dialog\Notification;

/**
 * Test class for YesNoCancelConfirmationDialog.
 * Generated by PHPUnit on 2012-07-02 at 23:19:38.
 */
class YesNoCancelConfirmationDialogTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var YesNoCancelConfirmationDialog
   */
  protected $dialog;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests creating the dialog.
   *
   * @covers \Woody\Dialog\FileSystem\YesNoCancelConfirmationDialog::__construct
   * @covers \Woody\Dialog\FileSystem\ConfirmationDialog::__construct
   * @covers \Woody\Dialog\FileSystem\ModalSystemDialog::__construct
   */
  public function YesNoCancelConfirmationDialog() {
    $this->dialog = new YesNoCancelConfirmationDialog('testConstruct', 'testConstruct', null);

    $this->assertInstanceOf('\Woody\Dialog\Notification\YesNoCancelConfirmationDialog', $this->dialog);
  }
}