<?php

namespace Woody\Dialog\Notification;

/**
 * Test class for YesNoConfirmationDialog.
 * Generated by PHPUnit on 2012-07-02 at 23:11:08.
 */
class YesNoConfirmationDialogTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var YesNoConfirmationDialog
   */
  protected $dialog;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests creating the dialog.
   *
   * @covers \Woody\Dialog\Notification\YesNoConfirmationDialog::__construct
   * @covers \Woody\Dialog\Notification\ConfirmationDialog::__construct
   * @covers \Woody\Dialog\Notification\ModalSystemDialog::__construct
   */
  public function testConstruct() {
    $this->dialog = new YesNoConfirmationDialog('testConstruct', 'testConstruct', null);

    $this->assertInstanceOf('\Woody\Dialog\Notification\YesNoConfirmationDialog', $this->dialog);
  }

  /**
   * This method tests getting the initial state of the dialog.
   *
   * @covers \Woody\Dialog\Notification\YesNoConfirmationDialog::yes
   * @covers \Woody\Dialog\Notification\YesNoConfirmationDialog::no
   */
  public function testYesNo() {
    $this->dialog = new YesNoConfirmationDialog('testConstruct', 'testConstruct', null);

    $this->assertFalse($this->dialog->yes());
    $this->assertFalse($this->dialog->no());
  }
}