<?php

namespace Woody\Event;

/**
 * Test class for ActionEvent.
 * Generated by PHPUnit on 2012-07-04 at 22:19:40.
 */
class ActionEventTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var ActionEvent the event to be tested
   */
  private $event = null;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->event = new ActionEvent(new EventInfo(0, 0, 0, 0, 0));
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests creating the event.
   *
   * @covers \Woody\Event\ActionEvent::__construct
   * @covers \Woody\Event\Event::__construct
   */
  public function testConstruct() {
    $this->assertInstanceOf('\Woody\Event\ActionEvent', $this->event);
  }

  /**
   * This method tests the string representation of the action event.
   *
   * @covers \Woody\Event\ActionEvent::__toString
   * @covers \Woody\Event\Event::__toString
   */
  public function testToString() {
    $this->assertTrue(strpos($this->event->__toString(), 'A/C/S = ') !== FALSE);
  }
}