<?php

namespace ws\loewe\Woody\Event;

/**
 * Test class for ActionAdapter.
 * Generated by PHPUnit on 2012-07-04 at 22:19:40.
 */
class ActionAdapterTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var ActionAdapter the adapter to test
   */
  private $adapter = null;

  /**
   * @var boolean simple flag to determine, if the callback was executed
   */
  private $callbackExecuted = 0;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method test the constructor of the adapter
   *
   * @covers ws\loewe\Woody\Event\ActionAdapter::__construct
   */
  public function testConstruct() {
    $this->adapter = new ActionAdapter(function(){});
    $this->assertInstanceOf('ws\loewe\Woody\Event\ActionAdapter', $this->adapter);
  }

  /**
   * This method test the callback execution when an action is performed gains focus.
   *
   * @covers ws\loewe\Woody\Event\ActionAdapter::actionPerformed
   */
  public function testActionPerformed() {
    $event = $this->getMockBuilder('\ws\loewe\Woody\Event\ActionEvent')
      ->disableOriginalConstructor()
      ->getMock();

    $this->adapter = new ActionAdapter(function(){$this->callbackExecuted = 1;});
    $this->assertEquals(0, $this->callbackExecuted);

    $this->adapter->actionPerformed($event);
    $this->assertEquals(1, $this->callbackExecuted);
  }
}