<?php

namespace Woody\Event;

/**
 * Test class for EventInfo.
 * Generated by PHPUnit on 2012-09-04 at 20:12:17.
 */
class EventInfoTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var EventInfo
   */
  private $eventInfo;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * @covers Woody\Event\EventInfo::isWindowEvent
   * @covers Woody\Event\EventInfo::__construct
   */
  public function testIsWindowEvent() {
    $this->eventInfo = new EventInfo(0, 0, 0, 0, 0);

    $this->assertTrue($this->eventInfo->isWindowEvent());
  }

  /**
   * @covers Woody\Event\EventInfo::isWindowResizeEvent
   */
  public function testIsWindowResizeEvent() {
    $this->eventInfo = new EventInfo(0, 0, 0, WBC_RESIZE, 0);

    $this->assertTrue($this->eventInfo->isWindowResizeEvent());
  }

  /**
   * @covers Woody\Event\EventInfo::isWindowCloseEvent
   */
  public function testIsWindowCloseEvent() {
    $this->eventInfo = new EventInfo(0, IDCLOSE, 0, 0, 0);

    $this->assertTrue($this->eventInfo->isWindowCloseEvent());
  }

  /**
   * @covers Woody\Event\EventInfo::isTimerEvent
   */
  public function testIsTimerEvent() {
    $this->eventInfo = new EventInfo(1, 1, 1, 0, 0);

    $this->assertTrue($this->eventInfo->isTimerEvent());
  }

  /**
   * @covers Woody\Event\EventInfo::isControlEvent
   */
  public function testIsControlEvent() {
    $this->eventInfo = new EventInfo(0, 1, 0, 0, 0);

    $this->assertTrue($this->eventInfo->isControlEvent());
  }

  /**
   * @covers Woody\Event\EventInfo::isFocusEvent
   */
  public function testIsFocusEvent() {
    $this->eventInfo = new EventInfo(0, 0, 0, WBC_GETFOCUS, 0);

    $this->assertTrue($this->eventInfo->isFocusEvent());
  }

  /**
   * @covers Woody\Event\EventInfo::isMouseEvent
   */
  public function testIsMouseEvent() {
    $this->eventInfo = new EventInfo(0, 0, 0, WBC_MOUSEDOWN, 0);

    $this->assertTrue($this->eventInfo->isMouseEvent());
  }

  /**
   * @covers Woody\Event\EventInfo::isKeyEvent
   */
  public function testIsKeyEvent() {
    $this->eventInfo = new EventInfo(0, 0, 0, WBC_KEYDOWN, 0);

    $this->assertTrue($this->eventInfo->isKeyEvent());
  }
}