<?php

namespace Woody\Event;

/**
 * Test class for EventFactory.
 * Generated by PHPUnit on 2012-09-04 at 22:37:42.
 */
class EventFactoryTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var EventFactory
   */
  private $factory = null;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers \Woody\Event\EventFactory::createEvent
   * @todo Implement testCreateEvent().
   */
  public function testCreateEvent() {
    //EventFactory::createEvent(new EventInfo(0, IDCLOSE, 0, 0, 0));
  }
}