<?php

namespace Woody\Event;

/**
 * Test class for FocusAdapter.
 * Generated by PHPUnit on 2012-06-26 at 21:13:02.
 */
class FocusAdapterTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var FocusAdapter the adapter to test
   */
  private $adapter = null;

  /**
   * @var boolean simple flag to determine, if the callback was executed
   */
  private $callbackExecuted = 0;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method test the constructor of the adapter
   *
   * @covers Woody\Event\FocusAdapter::__construct
   */
  public function testConstruct() {
    $this->adapter = new FocusAdapter(function(){});
    $this->assertInstanceOf('Woody\Event\FocusAdapter', $this->adapter);
  }

  /**
   * This method test the callback execution when a component gains focus.
   *
   * @covers Woody\Event\FocusAdapter::focusGained
   */
  public function testFocusGained() {
    $event = $this->getMockBuilder('\Woody\Event\FocusEvent')
      ->disableOriginalConstructor()
      ->getMock();

    $this->adapter = new FocusAdapter(function(){$this->callbackExecuted = 1;});
    $this->assertEquals(0, $this->callbackExecuted);

    $this->adapter->focusGained($event);
    $this->assertEquals(1, $this->callbackExecuted);
  }
}