<?php

namespace Woody\Event;

/**
 * Test class for KeyEvent.
 * Generated by PHPUnit on 2012-06-25 at 22:29:09.
 */
class KeyEventTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var KeyEvent
   */
  private $event = null;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->event = new KeyEvent(0, 0, 0, 0, 65);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests creating the event.
   *
   * @covers \Woody\Event\KeyEvent::__construct
   */
  public function testConstruct() {
    $this->assertInstanceOf('\Woody\Event\KeyEvent', $this->event);
  }

  /**
   * This method tests returning the character associated with the respective key.
   *
   * @covers \Woody\Event\KeyEvent::getPressedKey
   */
  public function testGetPressedKey() {
    $this->assertEquals('A', $this->event->getPressedKey());
  }

  /**
   * This method tests the string representation of the key event.
   *
   * @covers \Woody\Event\KeyEvent::__toString
   */
  public function testToString() {
    $this->assertNotNull($this->event->__toString());

    $this->assertTrue(strpos($this->event->__toString(), 'key = A') !== FALSE);
  }
}