<?php

namespace Woody\Event;

/**
 * Test class for TimeoutCloseAdapter.
 * Generated by PHPUnit on 2012-09-04 at 20:53:06.
 */
class TimeoutAdapterTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var TimeoutAdapter
   */
  private $adapter = null;

  /**
   * @var int simple counter to determine, how often the callback was executed
   */
  private $callbackExecuted = 0;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method test the constructor of the adapter
   *
   * @covers Woody\Event\TimeoutAdapter::__construct
   */
  public function testConstruct() {
    $this->adapter = new TimeoutAdapter(function(){});
    $this->assertInstanceOf('Woody\Event\TimeoutAdapter', $this->adapter);
  }

  /**
   * @covers Woody\Event\TimeoutAdapter::timeout
   */
  public function testTimeout() {
    $event = $this->getMockBuilder('Woody\Event\TimeoutEvent')
      ->disableOriginalConstructor()
      ->getMock();

    $this->adapter = new TimeoutAdapter(function(){$this->callbackExecuted = 1;});
    $this->assertEquals(0, $this->callbackExecuted);

    $this->adapter->timeout($event);
    $this->assertEquals(1, $this->callbackExecuted);
  }
}