<?php

namespace Woody\Event;

/**
 * Test class for WindowCloseEvent.
 * Generated by PHPUnit on 2012-09-04 at 20:57:12.
 */
class WindowCloseEventTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var WindowCloseEvent
   */
  protected $event;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->event = new WindowCloseEvent(new EventInfo(0, IDCLOSE, 0, 0, 0));
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests creating the event.
   *
   * @covers \Woody\Event\WindowCloseEvent::__construct
   * @covers \Woody\Event\Event::__construct
   */
  public function testConstruct() {
    $this->assertInstanceOf('\Woody\Event\WindowCloseEvent', $this->event);
  }
}