<?php

namespace Woody\Event;

/**
 * Test class for WindowResizeAdapter.
 * Generated by PHPUnit on 2012-09-04 at 20:47:40.
 */
class WindowResizeAdapterTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var WindowResizeAdapter
   */
  private $adapter = null;

  /**
   * @var int simple counter to determine, how often the callback was executed
   */
  private $callbackExecuted = 0;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method test the constructor of the adapter
   *
   * @covers Woody\Event\WindowResizeAdapter::__construct
   */
  public function testConstruct() {
    $this->adapter = new WindowResizeAdapter(function(){});
    $this->assertInstanceOf('Woody\Event\WindowResizeAdapter', $this->adapter);
  }

  /**
   * @covers Woody\Event\WindowResizeAdapter::windowResized
   */
  public function testWindowResized() {
    $event = $this->getMockBuilder('\Woody\Event\WindowResizeEvent')
      ->disableOriginalConstructor()
      ->getMock();

    $this->adapter = new WindowResizeAdapter(function(){$this->callbackExecuted = 1;});
    $this->assertEquals(0, $this->callbackExecuted);

    $this->adapter->windowResized($event);
    $this->assertEquals(1, $this->callbackExecuted);
  }
}