<?php

namespace Woody\Model;

/**
 * Test class for DefaultTableModelTest.
 * Generated by PHPUnit on 2011-11-30 at 22:59:58.
 */
class DefaultTableModelTest extends \PHPUnit_Framework_TestCase {

  /**
   * the table model to test
   *
   * @var DefaultTableModel
   */
  private $tableModel = null;

  /**
   * the raw data of the table model
   *
   * @var array
   */
  private $data       = null;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->data = array(array(1, 2, 3, 4), array(5, 6, 7 ,8));

    $this->tableModel = new DefaultTableModel($this->data);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests that creating the table model succeeds.
   *
   * @covers \Woody\Model\DefaultTableModel::__construct
   */
  public function testConstruct() {
    $this->tableModel = new DefaultTableModel(array(array(1, 2, 3, 4), array(4, 3, 2, 1)));
    $this->assertEquals(1, $this->tableModel->getEntry(0, 0));
    $this->assertEquals(4, $this->tableModel->getEntry(1, 0));
    $this->assertEquals(1, $this->tableModel->getEntry(1, 3));
  }

  /**
   * This method tests getting a cell entry.
   *
   * @covers \Woody\Model\DefaultTableModel::getEntry
   */
  public function testGetEntry() {
    $this->assertEquals(1, $this->tableModel->getEntry(0, 0));
    $this->assertEquals(2, $this->tableModel->getEntry(0, 1));
    $this->assertEquals(5, $this->tableModel->getEntry(1, 0));
    $this->assertEquals(6, $this->tableModel->getEntry(1, 1));
  }

  /**
   * This method tests retrieving the current number of rows.
   *
   * @covers \Woody\Model\DefaultTableModel::getRowCount
   */
  public function testGetRowCount() {
    $this->assertEquals(2, $this->tableModel->getRowCount());
  }

  /**
   * This method tests retrieving the current number of columns.
   *
   * @covers \Woody\Model\DefaultTableModel::getColumnCount
   */
  public function testGetColumnCount() {
    $this->assertEquals(4, $this->tableModel->getColumnCount());
  }

  /**
   * This method tests setting new data.
   *
   * @covers \Woody\Model\DefaultTableModel::setData
   */
  public function testSetData() {
    $this->assertEquals(1, $this->tableModel->getEntry(0, 0));

    $this->tableModel->setData(array(array('A1', 'B1'), array('A2', 'B2'), array('A3', 'B3')));
    $this->assertEquals('A1', $this->tableModel->getEntry(0, 0));
    $this->assertEquals('B1', $this->tableModel->getEntry(0, 1));
    $this->assertEquals('A2', $this->tableModel->getEntry(1, 0));
    $this->assertEquals('B2', $this->tableModel->getEntry(1, 1));
    $this->assertEquals('A3', $this->tableModel->getEntry(2, 0));
    $this->assertEquals('B3', $this->tableModel->getEntry(2, 1));
  }
}
