<?php

namespace Woody\Components\Controls;

use \Woody\App\TestApplication;
use \Woody\Components\Timer\Timer;
use \Woody\Utils\Geom\Point;
use \Woody\Utils\Geom\Dimension;

/**
 * Test class for Calendar.
 * Generated by PHPUnit on 2011-11-15 at 23:23:15.
 */
class CalendarTest extends \PHPUnit_Framework_TestCase
{
    /**
     * the calendar to test
     *
     * @var \Woody\Components\Controls\Calendar
     */
    private $calendar        = null;

    /**
     * the test application
     *
     * @var \Woody\App\TestApplication
     */
    private $application    = false;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->application = new TestApplication();

        $this->calendar = new Calendar(new Point(20, 20), new Dimension(197, 157));

        $this->application->getWindow()->add($this->calendar);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * This method tests retrieving the timestamp from the calendar.
     *
     * @covers \Woody\Components\Controls\Calendar::getTimestamp
     */
    public function testGetTimestamp()
    {
        $this->timer = new Timer(function()
                        {
                            $this->assertEquals(mktime(0, 0, 0, date('m', time()), date('d', time()), date('Y', time())), $this->calendar->getTimestamp());
                            $this->timer->destroy();

                            $this->application->stop();
                        }, $this->application->getWindow(), 100);

        $this->timer->start($this->application->getWindow());

        $this->application->start();
    }

    /**
     * This method tests setting the timestamp from the calendar.
     *
     * @covers \Woody\Components\Controls\Calendar::setTimestamp
     */
    public function testSetTimestamp()
    {
        $this->timer = new Timer(function()
                        {
                            $this->calendar->setTimestamp(1);
                            //$this->assertEquals(1, $this->calendar->getTimestamp());
                            $this->timer->destroy();

                            $this->application->stop();
                        }, $this->application->getWindow(), 100);

        $this->timer->start($this->application->getWindow());

        $this->application->start();
    }
}