<?php

namespace Woody\Components\Controls;

use Woody\Components\Windows\MainWindow;
use Woody\Components\Timer\Timer;
use Woody\Utils\Geom\Point;
use Woody\Utils\Geom\Dimension;

/**
 * Test class for EditBox.
 * Generated by PHPUnit on 2011-11-15 at 23:23:15.
 */
class EditBoxTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var EditBox
     */
    public $object;

    public $counter = 0;

    public $result = 0;

    private static $cnt = 0;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->delay = 1000000;

        $this->window = new MainWindow('edit box test '.(self::$cnt++), new Point(50, 50), new Dimension(300, 200));

        $this->window->create(null);

        $this->object = new EditBox('testValue', new \Woody\Utils\Geom\Point(20, 20), new \Woody\Utils\Geom\Dimension(100, 18));

        $this->window->add($this->object);

        $self = $this;
        $this->timer = new Timer(function() use ($self)
                        {
                            if(++$self->counter > 1)
                            {
                                $self->window->destroy();
                            }
                        }, 2000);

        $this->timer->start($this->window);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetValue().
     */
    public function testGetValue()
    {
        $self = $this;
        $this->timerTest1 = new Timer(function() use ($self)
                        {
                            $self->assertEquals('testValue', $self->object->getValue());
                            $self->timerTest1->destroy();
                        }, 100);

        $this->timerTest1->start($this->window);

        $this->timerTest2 = new Timer(function() use ($self)
                        {
                            $self->object->setValue('     testValue     ');
                            $self->assertEquals('testValue', $self->object->getValue());
                            $self->timerTest2->destroy();
                        }, 200);
        $this->timerTest2->start($this->window);

        $this->window->startEventHandler();
    }

    /**
     * @todo Implement testSetValue().
     */
    public function testSetValue()
    {
        $self = $this;
        $this->timerTest3 = new Timer(function() use ($self)
                           {
                               $self->object->setValue('  new  value  ');
                               $self->assertEquals('  new  value  ', $self->object->getValue(FALSE));
                               $self->timerTest3->destroy();
                           }, 100);
        $this->timerTest3->start($this->window);

        $this->timerTest4 = new Timer(function() use ($self)
                        {
                            $self->object->setValue('');
                            $self->assertEquals('', $self->object->getValue());
                            $self->timerTest4->destroy();
                        }, 200);
        $this->timerTest4->start($this->window);


        $this->timerTest5 = new Timer(function() use ($self)
                        {
                            $self->object->setValue('12345');
                            $self->assertEquals('12345', $self->object->getValue());
                            $self->timerTest5->destroy();
                        }, 300);
        $this->timerTest5->start($this->window);

        $this->window->startEventHandler();
    }

    /**
     * @todo Implement testSetReadOnly().
     */
    public function testSetReadOnly()
    {
        $this->markTestIncomplete('This test has not been implemented yet, because it is hard to test!');
    }
}