<?php

namespace Woody\Components\Controls;

use \Woody\App\TestApplication;
use \Woody\Components\Timer\Timer;
use \Woody\Utils\Geom\Point;
use \Woody\Utils\Geom\Dimension;

/**
 * Test class for HTMLControl.
 * Generated by PHPUnit on 2011-11-24 at 17:24:08.
 */
class HTMLControlTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HTMLControl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->application = new TestApplication();

        $this->htmlControl = new HTMLControl('testValue', new Point(20, 20), new Dimension(100, 18));

        $this->application->getWindow()->add($this->editBox);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetUrl().
     */
    public function testGetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testSetUrl().
     */
    public function testSetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
