<?php

namespace Woody\Components\Controls;

use \Woody\App\TestApplication;
use \Woody\Components\Timer\Timer;
use \Utils\Geom\Point;
use \Utils\Geom\Dimension;
use \Woody\Model\ListModel;


/**
 * Test class for ListView.
 * Generated by PHPUnit on 2011-12-05 at 22:43:16.
 */
class ListViewTest extends \PHPUnit_Framework_TestCase {

    /**
     * the listbox under test
     *
     * @var \Woody\Components\Controls\ListView
     */
    private $combobox       = null;

    /**
     * the test application
     *
     * @var \Woody\App\TestApplication
     */
    private $application    = false;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->application = new TestApplication();

        $this->combobox = new ListBox(new Point(20, 20), new Dimension(80, 200));

        $this->application->getWindow()->add($this->combobox);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }
}