<?php

namespace Woody\Components\Controls;

use \Woody\App\TestApplication;
use \Woody\Components\Timer\Timer;
use \Utils\Geom\Point;
use \Utils\Geom\Dimension;
use \Woody\Model\ListModel;

/**
 * Test class for ListBox.
 * Generated by PHPUnit on 2011-12-05 at 22:44:52.
 */
class ListBoxTest extends \PHPUnit_Framework_TestCase {

    /**
     * the combobox under test
     *
     * @var \Woody\Components\Controls\ComboBox
     */
    private $listbox       = null;

    /**
     * the test application
     *
     * @var \Woody\App\TestApplication
     */
    private $application    = false;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->application  = new TestApplication();

        $this->listbox     = new ListBox(new Point(20, 20), new Dimension(80, 200));

        $this->application->getWindow()->add($this->listbox);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers \Woody\Components\Controls\Combobox::getModel
     */
    public function testGetModel() {
        $this->timer = new Timer(function() {
                            $this->assertNull($this->listbox->getModel());

                            $stubModel = $this->getMockBuilder('\Woody\Model\ListModel')
                                ->disableOriginalConstructor()
                                ->getMock();
                            $this->listbox->setModel($stubModel);
                            $this->assertNotNull($this->listbox->getModel());

                            $this->timer->destroy();
                            $this->application->stop();
                        }, $this->application->getWindow(), 100);

        $this->timer->start($this->application->getWindow());

        $this->application->start();
    }

    /**
     * @covers \Woody\Components\Controls\Combobox::setModel
     */
    public function testSetModel() {
        $this->timer = new Timer(function() {
                            $this->assertNull($this->listbox->getModel());

                            $stubModel = $this->getMockBuilder('\Woody\Model\ListModel')
                                 ->disableOriginalConstructor()
                                 ->getMock();
                            $this->listbox->setModel($stubModel);
                            $this->assertNotNull($this->listbox->getModel());
                            $this->assertSame($stubModel, $this->listbox->getModel());


                            $this->timer->destroy();
                            $this->application->stop();
                        }, $this->application->getWindow(), 100);

        $this->timer->start($this->application->getWindow());

        $this->application->start();
    }

    /**
     * @covers \Woody\Components\Controls\Combobox::update
     */
    public function testUpdate() {
        $this->timer = new Timer(function() {
                            $this->listbox->setModel($model = new ListModel(new \ArrayObject()));

                            $model->attach($this->listbox);
                            $model->addElement('1');

                            $this->listbox->setSelectedIndex(0);

                            $this->assertEquals('1', $this->listbox->getSelectedElement());


                            $this->timer->destroy();
                            $this->application->stop();
                        }, $this->application->getWindow(), 100);

        $this->timer->start($this->application->getWindow());

        $this->application->start();
    }

    /**
     * @covers \Woody\Components\Controls\Combobox::getSelectedIndex
     */
    public function testGetSelectedIndex() {
        $this->timer = new Timer(function() {
                            $this->assertEquals(-1, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(10);
                            $this->assertEquals(-1, $this->listbox->getSelectedIndex());

                            $this->listbox->setModel($model = new ListModel(new \ArrayObject()));

                            $model->attach($this->listbox);
                            $model->addElement('one');
                            $model->addElement('two');

                            $this->assertEquals(0, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals(1, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals(1, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(2);
                            $this->assertEquals(1, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(-1);
                            $this->assertEquals(-1, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals(1, $this->listbox->getSelectedIndex());


                            $this->timer->destroy();
                            $this->application->stop();
                        }, $this->application->getWindow(), 100);

        $this->timer->start($this->application->getWindow());

        $this->application->start();
    }

    /**
     * @covers \Woody\Components\Controls\Combobox::setSelectedIndex
     */
    public function testSetSelectedIndex() {
        $this->timer = new Timer(function() {
                            $this->assertEquals(-1, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(10);
                            $this->assertEquals(-1, $this->listbox->getSelectedIndex());

                            $this->listbox->setModel($model = new ListModel(new \ArrayObject()));

                            $model->attach($this->listbox);
                            $model->addElement('one');
                            $model->addElement('two');

                            $this->assertEquals(0, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals(1, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(2);
                            $this->assertEquals(1, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(-1);
                            $this->assertEquals(-1, $this->listbox->getSelectedIndex());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals(1, $this->listbox->getSelectedIndex());


                            $this->timer->destroy();
                            $this->application->stop();
                        }, $this->application->getWindow(), 100);

        $this->timer->start($this->application->getWindow());

        $this->application->start();
    }

    /**
     * @covers \Woody\Components\Controls\Combobox::getSelectedElement
     */
    public function testGetSelectedElement() {
        $this->timer = new Timer(function() {
                            $this->assertEquals(null, $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(10);
                            $this->assertEquals(null, $this->listbox->getSelectedElement());

                            $this->listbox->setModel($model = new ListModel(new \ArrayObject()));

                            $model->attach($this->listbox);
                            $model->addElement('one');
                            $model->addElement('two');

                            $this->assertEquals('one', $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals('two', $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals('two', $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(2);
                            $this->assertEquals('two', $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(-1);
                            $this->assertEquals(null, $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals('two', $this->listbox->getSelectedElement());


                            $this->timer->destroy();
                            $this->application->stop();
                        }, $this->application->getWindow(), 100);

        $this->timer->start($this->application->getWindow());

        $this->application->start();
    }

    /**
     * @covers \Woody\Components\Controls\Combobox::setSelectedElement
     */
    public function testSetSelectedElement() {
        $this->timer = new Timer(function() {
                            $this->assertEquals(null, $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(10);
                            $this->assertEquals(null, $this->listbox->getSelectedElement());

                            $this->listbox->setModel($model = new ListModel(new \ArrayObject()));

                            $model->attach($this->listbox);
                            $model->addElement('one');
                            $model->addElement('two');

                            $this->assertEquals('one', $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals('two', $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals('two', $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(2);
                            $this->assertEquals('two', $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(-1);
                            $this->assertEquals(null, $this->listbox->getSelectedElement());

                            $this->listbox->setSelectedIndex(1);
                            $this->assertEquals('two', $this->listbox->getSelectedElement());


                            $this->timer->destroy();
                            $this->application->stop();
                        }, $this->application->getWindow(), 100);

        $this->timer->start($this->application->getWindow());

        $this->application->start();
    }
}