<?php

namespace ws\loewe\Woody\Components\Controls;

use \ws\loewe\Woody\App\TestApplication;
use \ws\loewe\Woody\Components\Timer\Timer;
use \ws\loewe\Utils\Geom\Point;
use \ws\loewe\Utils\Geom\Dimension;

/**
 * Test class for ProgressBar.
 * Generated by PHPUnit on 2011-12-18 at 19:31:01.
 */
class ProgressBarTest extends \PHPUnit_Framework_TestCase {

  /**
   * the progress bar to test
   *
   * @var \ws\loewe\Woody\Components\Controls\Progressbar
   */
  private $progressBar = null;

  /**
   * the test application
   *
   * @var \ws\loewe\Woody\App\TestApplication
   */
  private $application = null;

  /**
   * the timer for the test application
   *
   * @var \ws\loewe\Woody\Components\Timer\Timer
   */
  private $timer = null;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->application = new TestApplication();

    $this->progressBar = new ProgressBar(new Point(20, 20), new Dimension(80, 20));

    $this->application->getWindow()->getRootPane()->add($this->progressBar);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * @covers \ws\loewe\Woody\Components\Controls\ProgressBar::getProgress
   * @covers \ws\loewe\Woody\Components\Controls\ProgressBar::setProgress
   */
  public function testGetSetValue() {
    $this->timer = new Timer(function() {
                              $this->assertEquals(0, $this->progressBar->getProgress());

                              $this->progressBar->setProgress(100);
                              $this->assertEquals(100, $this->progressBar->getProgress());

                              $this->timer->destroy();
                              $this->application->stop();
                            }, $this->application->getWindow(), Timer::TEST_TIMEOUT);

    $this->timer->start();

    $this->application->start();
  }

  /**
   * @covers \ws\loewe\Woody\Components\Controls\ProgressBar::setRange
   */
  public function testSetRange() {
    $this->timer = new Timer(function() {
                              $this->assertEquals(0, $this->progressBar->getProgress());

                              $this->progressBar->setRange(0, Timer::TEST_TIMEOUT);
                              $this->progressBar->setProgress(100);
                              $this->assertEquals(100, $this->progressBar->getProgress());

                              $this->timer->destroy();
                              $this->application->stop();
                            }, $this->application->getWindow(), Timer::TEST_TIMEOUT);

    $this->timer->start();

    $this->application->start();
  }
}