<?php

namespace ws\loewe\Woody\Components\Controls;

use \ws\loewe\Woody\App\TestApplication;
use \ws\loewe\Woody\Components\Timer\Timer;
use \ws\loewe\Utils\Geom\Point;
use \ws\loewe\Utils\Geom\Dimension;

/**
 * Test class for Tab.
 * Generated by PHPUnit on 2012-08-29 at 13:34:20.
 */
class TabTest extends \PHPUnit_Framework_TestCase {
  /**
   * @var Tab
   */
  protected $tab;

  /**
   * the test application
   *
   * @var \ws\loewe\Woody\App\TestApplication
   */
  private $application = null;

  /**
   * the timer for the test application
   *
   * @var \ws\loewe\Woody\Components\Timer\Timer
   */
  private $timer = null;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->application = new TestApplication();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * This method tests adding pages to and getting pages from the tab control.
   *
   * @covers ws\loewe\Woody\Components\Controls\Tab::addTabPage
   * @covers ws\loewe\Woody\Components\Controls\Tab::getTabPage
   */
  public function testAddPage() {
    $callback = function() {
      $this->timer->destroy();
      $this->application->stop();
    };

    $this->timer = new Timer($callback, $this->application->getWindow(), Timer::TEST_TIMEOUT);
    $this->timer->start();

    $this->tab   = new Tab(Point::createInstance(10, 10), Dimension::createInstance(200, 100));
    $this->application->getWindow()->getRootPane()->add($this->tab);
    $this->tab->addTabPage('tab1');
    $this->tab->addTabPage('tab2');

    $tabPage1 = $this->tab->getTabPage('tab1');
    $tabPage2 = $this->tab->getTabPage('tab2');

    $tabPage1->add(new EditBox('box 1.1', Point::createInstance(5, 15), Dimension::createInstance(50, 20)));
    $tabPage1->add(new EditBox('box 1.2', Point::createInstance(65, 15), Dimension::createInstance(50, 20)));

    $tabPage2->add(new EditBox('box 2.1', Point::createInstance(5, 15), Dimension::createInstance(50, 20)));
    $tabPage2->add(new EditBox('box 2.2', Point::createInstance(5, 45), Dimension::createInstance(50, 20)));

    $this->application->start();
  }
}