<?php

namespace Woody\Components\Controls;

use \Woody\App\TestApplication;
use \Woody\Components\Timer\Timer;
use \Utils\Geom\Point;
use \Utils\Geom\Dimension;

/**
 * Test class for Tab.
 * Generated by PHPUnit on 2012-08-29 at 13:34:20.
 */
class TabTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Tab
   */
  protected $tab;

  /**
   * the test application
   *
   * @var \Woody\App\TestApplication
   */
  private $application = false;

  /**
   * the timer for the test application
   *
   * @var \Woody\Components\Timer\Timer
   */
  private $timer = null;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->application = new TestApplication();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * @covers  Woody\Components\Controls\Tab::addPage
   */
  public function testAddPage() {
    $callback = function() {
                              $this->timer->destroy();
                              $this->application->stop();
    };

    $this->timer = new Timer($callback, $this->application->getWindow(), Timer::TEST_TIMEOUT);

    $this->timer->start();

    $tab = new Tab(new Point(10, 10), new Dimension(200, 100));
    $this->application->getWindow()->getRootPane()->add($tab);
    $tab->addPage("t1");
    $tab->addPage("t2");

    $tab->getTabPage(0)->add(new EditBox('new', new Point(5, 5), new Dimension(50, 20)));
    $tab->getTabPage(0)->add(new EditBox('new2', new Point(25, 5), new Dimension(50, 20)));

    $tab->getTabPage(1)->add(new EditBox('new21', new Point(5, 15), new Dimension(50, 20)));
    $tab->getTabPage(1)->add(new EditBox('new22', new Point(25, 15), new Dimension(50, 20)));

    $this->application->start();
  }
}